---
# https://prettier.io/docs/en/options.html#semicolons
semi: true

# https://prettier.io/docs/en/options.html#trailing-commas
trailingComma: 'es5'

# https://prettier.io/docs/en/options.html#quotes
singleQuote: true

# https://prettier.io/docs/en/options.html#jsx-quotes
jsxSingleQuote: true

# https://prettier.io/docs/en/options.html#print-width
printWidth: 100

# https://prettier.io/docs/en/options.html#tab-width
tabWidth: 2

# https://prettier.io/docs/en/options.html#bracket-spacing
bracketSpacing: true

# https://prettier.io/docs/en/options.html#arrow-function-parentheses
arrowParens: 'always'
